In [1]:
## lets imagine a simple neural network with two nodes.

In [440]:
import numpy as np

In [441]:
X = np.array([[1,1,0,1,0,1,1,0,0]])

In [442]:
Y = np.array([0,0,1,0,1,0,0,1,1])

In [443]:
# sigma function
sigma = lambda z : np.tanh(z) # sigma function 
d_sigma = lambda z : 1 - np.tanh(z)**(2) # first diffrential

In [444]:
# assign random values to A.B
W = np.random.randn(1)
b = np.random.randn(1)

In [445]:
def forward_feed(a0) :
    z = W @ a0 + b
    a1 = sigma(z)
    return a0, a1, z

In [454]:
def cost(a1, y) :
    return np.sum((a1 - y)**2) / a1.size

In [447]:
#a0, a1, z = forward_feed(X)

In [455]:
# deffrential function dc/db
def J_b (x, y) :
    a0, a1, z = forward_feed(x)
    J = 2 * (a1 - y) # dc/da1
    J = J * d_sigma(z) # dc/da1 * da1/dz * dz/db Note: dz/db = 1 
    J = np.sum(J) / x.size
    return J

In [449]:
# deffrential function dc/dw
def J_w (x, y) :
    a0, a1, z = forward_feed(x)
    J = 2 * (a1 - y) # dc/da1
    J = J * d_sigma(z) # dc/da1 * da1/dz
    J = J @ a0.T / x.size # 
    return J    

In [456]:
def back_prop (x, y, W, b, iterations=50000, stepsize=.01) :
    while iterations>=0 :
        W = W - J_w (x, y) * stepsize
        b = b - J_b (x, y) * stepsize
        iterations -= 1
        
    return W , b

In [457]:
back_prop(X,Y, W, b)

(array([-5.]), array([5.00000733]))

In [452]:
W = np.array([-5])
b = np.array([5])

In [458]:
forward_feed(X)

(array([[1, 1, 0, 1, 0, 1, 1, 0, 0]]),
 array([0.       , 0.       , 0.9999092, 0.       , 0.9999092, 0.       ,
        0.       , 0.9999092, 0.9999092]),
 array([0, 0, 5, 0, 5, 0, 0, 5, 5]))